Ground work for demo application
Lukasz825700516/KPZ-2024-traffic_lights pull request #24
Opened 2024-04-10 14:57 UTC by Lukasz825700516

I prepared some ground work for the video handling. From this point it should be relatively easy to annotate graphically frames for show or something.

2024-04-10 14:58 UTC, Lukasz825700516 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Wykrywanie w czasie rzeczywistym](https://trello.com/c/xtWuEQ5h/16-wykrywanie-w-czasie-rzeczywistym)

2024-04-10 14:59 UTC, Lukasz825700516 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dane z kamery](https://trello.com/c/t2feRjsY/18-dane-z-kamery)

2024-04-11 07:45 UTC, Iamhexi requested changes

2024-04-11 07:45 UTC, Iamhexi commented on scripts/yolop_zebra_crossing.py
>          frame = cv2.resize(frame, dsize=(640, 640), interpolation=cv2.INTER_CUBIC)
Cubic interpolation is slow. You had better used linear interpolation.

Source: https://web.archive.org/web/20190424180810/http://tanbakuchi.com/posts/comparison-of-openv-interpolation-algorithms/

2024-04-11 09:16 UTC, Iamhexi approved these changes
Great job!

2024-04-11 09:16 UTC, merged