Live demo
Lukasz825700516/KPZ-2024-traffic_lights pull request #27
Opened 2024-04-11 20:35 UTC by dawid-sz22

#9 #11

2024-04-11 20:52 UTC, Lukasz825700516 requested changes

2024-04-11 20:52 UTC, Lukasz825700516 commented on scripts/yolov8n.pt
Please move this binary blob out of the scripts directory. Otherwise looks good for a demo.

2024-04-11 21:40 UTC, Iamhexi submitted a review, later dismissed

2024-04-11 21:40 UTC, Iamhexi commented on scripts/live_demo_v2.py
> +        # time.sleep(0.1)
Do **not** keep comments without clear purpose. Either uncomment this line or remove.

2024-04-12 13:26 UTC, Lukasz825700516 approved these changes

2024-04-12 13:27 UTC, merged