feat: develop terminal app
Lukasz825700516/KPZ-2024-traffic_lights pull request #31
Opened 2024-04-19 11:40 UTC by Iamhexi

A terminal app displaying in a terminal traffic lights' color (for now, red or green only) with a timer counting down.

Example:
![image](https://github.com/Lukasz825700516/KPZ-2024-traffic_lights/assets/20840572/4f9ab634-638f-4ff9-a302-5f574582c05e)

2024-04-19 13:02 UTC, Lukasz825700516 requested changes
TBH, we should use some python package for command line argument parsing and validation.

2024-04-19 13:02 UTC, Lukasz825700516 commented on scripts/demo/live_demo_v3.py
> +    classes = ['Elderly', 'Child', 'Adult', 'Wheelchair', 'Blind', 'Suitcase', 'Stroller']
`classes = time_increment.keys()`

2024-04-19 18:20 UTC, Lukasz825700516 requested changes
IO had sense xd, without functional requirements we are just writing something that does what one person thinks it should, and there is no real ground to tell if given part of code is useless or useful.

2024-04-19 18:20 UTC, Lukasz825700516 commented on scripts/demo/TrafficLights.py
> +        if not self.__is_running:
I don't like there is possibility that `update()` could fail silently when `__is_running` is false.

2024-04-19 18:20 UTC, Lukasz825700516 commented on scripts/demo/TrafficLights.py
> +            elif self.__state == LightState.GREEN:
just `match... case`, there is no need for else as previous `if` just runs continue

2024-04-19 18:20 UTC, Lukasz825700516 commented on scripts/demo/TrafficLights.py
> +                self.__time_left = self.__base_red_duration
`match... case`

2024-04-19 18:20 UTC, Lukasz825700516 commented on scripts/demo/TrafficLights.py
> +        if self.__time_left < 0:
```python
if not self.__time_left < 0:
    continue
```

2024-04-20 13:08 UTC, Iamhexi commented on scripts/demo/TrafficLights.py
> +    def display(self) -> None:
Because it clears the content of the terminal.

2024-04-21 15:27 UTC, Iamhexi commented on scripts/demo/TrafficLights.py
> +        if self.__time_left < 0:
Traffic lights change their state when an internal counter reaches 0.

2024-04-21 15:32 UTC, Iamhexi commented on scripts/demo/TrafficLights.py
> +                self.__time_left = self.__base_red_duration
I requires at least Python 3.10.

2024-04-21 15:37 UTC, Iamhexi commented on scripts/demo/TrafficLights.py
> +    def __convert_class_ID_to_name(self, class_id: int) -> str:
It is clearer to convey that meaning with a function name instead of using two `self.__classes[ class_id ]`. The latter may be confusing for the person reading the code and is **not** self-explanatory.

2024-04-21 15:54 UTC, Iamhexi commented on scripts/demo/live_demo_v3.py
> +
Could you possibly write a standard to keep the project coherent? :eye: :eye:

2024-04-21 16:47 UTC, Lukasz825700516 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Demo symulator świateł](https://trello.com/c/b3ojlUfT/25-demo-symulator-%C5%9Bwiate%C5%82)

2024-04-21 16:49 UTC, Lukasz825700516 approved these changes
looks good

2024-04-21 19:22 UTC, merged